/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:b80e277a-df2c-4ff0-b3f1-b248e849c7a7",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_gJhYr7bDE",
    "aws_user_pools_web_client_id": "2pqjrdjnqjgqkjbnidiqrdhucc",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fh3o4kawezceplz3vrtnokjemu.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
